name: Build IHP Documentation and API Reference
on:
  push:
    branches: 'master'
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        determinate: true
        extra-conf: "lazy-trees = true"
    - uses: cachix/cachix-action@v16
      with:
        name: digitallyinduced
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build Docs
      run: nix build .#guide
    - name: Build API Reference
      run: nix build .#reference
